# Generated by Django 4.2.16 on 2024-09-28 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollee_id', models.IntegerField(unique=True)),
                ('city', models.CharField(max_length=20)),
                ('city_development_index', models.FloatField()),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True)),
                ('relevent_experience', models.BooleanField(default=False)),
                ('enrolled_university', models.CharField(choices=[('no_enrollment', 'No Enrollment'), ('Full time course', 'Full Time Course'), ('Part time course', 'Part Time Course')], default='no_enrollment', max_length=50)),
                ('education_level', models.CharField(choices=[('Graduate', 'Graduate'), ('Masters', 'Masters'), ('High School', 'High School')], max_length=20)),
                ('major_discipline', models.CharField(blank=True, choices=[('STEM', 'STEM'), ('Business Degree', 'Business Degree'), ('Humanities', 'Humanities'), ('Arts', 'Arts')], max_length=50, null=True)),
                ('experience', models.CharField(max_length=10)),
                ('company_size', models.CharField(blank=True, choices=[('<10', '<10'), ('10-49', '10-49'), ('50-99', '50-99'), ('100-500', '100-500'), ('500-999', '500-999'), ('1000-4999', '1000-4999'), ('5000-9999', '5000-9999'), ('10000+', '10000+'), ('Oct-49', 'Oct-49')], max_length=20, null=True)),
                ('company_type', models.CharField(blank=True, choices=[('Pvt Ltd', 'Private Limited'), ('Funded Startup', 'Funded Startup')], max_length=50, null=True)),
                ('last_new_job', models.CharField(blank=True, choices=[('never', 'Never'), ('1', '1 Year'), ('2', '2 Years'), ('3', '3 Years'), ('4', '4 Years'), ('>4', 'More than 4 Years')], max_length=10, null=True)),
                ('training_hours', models.IntegerField()),
                ('target', models.BooleanField(default=False)),
            ],
        ),
    ]
