# Generated by Django 4.2.16 on 2024-09-28 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollee',
            name='enrollee_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
