# Generated by Django 4.2.16 on 2024-09-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_alter_enrollee_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollee',
            name='experience',
            field=models.CharField(choices=[('Has relevent experience', 'Has relevent experience'), ('No relevent experience', 'No relevent experience')], max_length=150, null=True),
        ),
    ]
