# Generated by Django 4.2.16 on 2024-09-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_alter_enrollee_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollee',
            name='city_development_index',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='enrollee',
            name='enrollee_id',
            field=models.CharField(max_length=20),
        ),
    ]
